# Generated by Django 3.2 on 2021-05-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_orderitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
